from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import os
import re
import json
import secrets
from datetime import datetime, timezone
from uuid import uuid4
from dotenv import load_dotenv
from openai import AzureOpenAI
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv()

app = FastAPI(title="SketchSQL API")

# MongoDB (for shared-diagram snapshots)
_mongo_client = AsyncIOMotorClient(os.environ["MONGO_URL"])
_db = _mongo_client[os.environ["DB_NAME"]]
shares_coll = _db["shares"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Azure OpenAI client (lazy init)
_azure_client = None

def get_client():
    global _azure_client
    if _azure_client is None:
        _azure_client = AzureOpenAI(
            azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT", ""),
            api_key=os.environ.get("AZURE_OPENAI_API_KEY", ""),
            api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-12-01-preview"),
        )
    return _azure_client

DEPLOYMENT = lambda: os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-5.4")

# ─── Pydantic Models ────────────────────────────────────────────────────────

class Column(BaseModel):
    id: str
    name: str
    type: str
    primaryKey: bool = False
    autoIncrement: bool = False
    nullable: bool = True
    unique: bool = False
    defaultValue: str = ""

class Table(BaseModel):
    id: str
    name: str
    color: str = "gray"
    columns: List[Column] = []
    position: Optional[Dict[str, float]] = None

class Relationship(BaseModel):
    id: str
    sourceTableId: str
    sourceColumnId: str
    targetTableId: str
    targetColumnId: str
    type: str = "one-to-many"
    onDelete: str = "RESTRICT"
    onUpdate: str = "RESTRICT"
    label: str = ""

class Diagram(BaseModel):
    id: Optional[str] = None
    name: str = "Untitled"
    dialect: str = "mysql"
    tables: List[Table] = []
    relationships: List[Relationship] = []

class GenerateSqlRequest(BaseModel):
    diagram: Diagram
    dialect: str = "mysql"

class ImportSqlRequest(BaseModel):
    sql: str
    dialect: str = "mysql"

class AiGenerateSchemaRequest(BaseModel):
    prompt: str

class AiAnalyzeSchemaRequest(BaseModel):
    diagram: Diagram
    dialect: str = "mysql"

class ChatMessage(BaseModel):
    role: str
    content: str

class AiChatRequest(BaseModel):
    messages: List[ChatMessage]
    diagram: Diagram
    dialect: str = "mysql"

# ─── SQL Generator ──────────────────────────────────────────────────────────

def q(name: str, dialect: str) -> str:
    return f"`{name}`" if dialect == "mysql" else f'"{name}"'

def pg_type(col_type: str, auto_increment: bool) -> str:
    t = col_type.upper()
    if auto_increment:
        if "BIGINT" in t:
            return "BIGSERIAL"
        if "INT" in t:
            return "SERIAL"
    if t == "DATETIME":
        return "TIMESTAMP"
    if t.startswith("TINYINT"):
        return "BOOLEAN"
    return col_type

def topological_sort(tables: List[Table], relationships: List[Relationship]) -> List[Table]:
    tmap = {t.id: t for t in tables}
    deps: Dict[str, set] = {t.id: set() for t in tables}
    for rel in relationships:
        if rel.type != "many-to-many":
            if rel.sourceTableId in deps and rel.targetTableId in tmap:
                deps[rel.sourceTableId].add(rel.targetTableId)
    visited: set = set()
    result: List[Table] = []

    def dfs(tid: str):
        if tid in visited:
            return
        visited.add(tid)
        for dep in deps.get(tid, set()):
            dfs(dep)
        if tid in tmap:
            result.append(tmap[tid])

    for t in tables:
        dfs(t.id)
    return result

def fmt_default(dv: str) -> str:
    keywords = {"NULL", "CURRENT_TIMESTAMP", "TRUE", "FALSE", "NOW()", "CURRENT_DATE", "CURRENT_TIME"}
    if dv.upper() in keywords or dv.lstrip("-").isdigit():
        return dv
    return f"'{dv}'"

def generate_mysql(diagram: Diagram) -> str:
    tables, rels = diagram.tables, diagram.relationships
    sorted_tables = topological_sort(tables, rels)
    tmap = {t.id: t for t in tables}
    cmap = {c.id: c for t in tables for c in t.columns}
    parts = ["-- Generated by SketchSQL\n-- Dialect: MySQL\n\nSET FOREIGN_KEY_CHECKS=0;\n"]

    for table in sorted_tables:
        col_defs, pks = [], []
        for col in table.columns:
            defn = f"  {q(col.name, 'mysql')} {col.type}"
            if col.autoIncrement and col.primaryKey:
                defn += " AUTO_INCREMENT"
            if not col.nullable or col.primaryKey:
                defn += " NOT NULL"
            if col.unique and not col.primaryKey:
                defn += " UNIQUE"
            if col.defaultValue:
                defn += f" DEFAULT {fmt_default(col.defaultValue)}"
            col_defs.append(defn)
            if col.primaryKey:
                pks.append(col.name)
        if pks:
            col_defs.append(f"  PRIMARY KEY ({', '.join(q(p, 'mysql') for p in pks)})")
        parts.append(
            f"CREATE TABLE {q(table.name, 'mysql')} (\n" +
            ",\n".join(col_defs) +
            "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
        )

    # Many-to-many junction tables
    for rel in rels:
        if rel.type != "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        jn = f"{src.name}_{tgt.name}"
        sf, tf = f"{src.name}_id", f"{tgt.name}_id"
        spk = next((c for c in src.columns if c.primaryKey), None)
        tpk = next((c for c in tgt.columns if c.primaryKey), None)
        st = (spk.type if spk else "INT").split("(")[0]
        tt = (tpk.type if tpk else "INT").split("(")[0]
        od, ou = rel.onDelete or "CASCADE", rel.onUpdate or "CASCADE"
        parts.append(
            f"CREATE TABLE {q(jn, 'mysql')} (\n"
            f"  {q(sf, 'mysql')} {st} NOT NULL,\n"
            f"  {q(tf, 'mysql')} {tt} NOT NULL,\n"
            f"  PRIMARY KEY ({q(sf, 'mysql')}, {q(tf, 'mysql')}),\n"
            f"  FOREIGN KEY ({q(sf, 'mysql')}) REFERENCES {q(src.name, 'mysql')}({q(sc.name, 'mysql')}) ON DELETE {od} ON UPDATE {ou},\n"
            f"  FOREIGN KEY ({q(tf, 'mysql')}) REFERENCES {q(tgt.name, 'mysql')}({q(tc.name, 'mysql')}) ON DELETE {od} ON UPDATE {ou}\n"
            f") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
        )

    # FK constraints
    for rel in rels:
        if rel.type == "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        od, ou = rel.onDelete or "RESTRICT", rel.onUpdate or "RESTRICT"
        fk = f"fk_{src.name}_{sc.name}"
        parts.append(
            f"ALTER TABLE {q(src.name, 'mysql')}\n"
            f"  ADD CONSTRAINT {q(fk, 'mysql')}\n"
            f"  FOREIGN KEY ({q(sc.name, 'mysql')})\n"
            f"  REFERENCES {q(tgt.name, 'mysql')}({q(tc.name, 'mysql')})\n"
            f"  ON DELETE {od} ON UPDATE {ou};\n"
        )

    parts.append("\nSET FOREIGN_KEY_CHECKS=1;")
    return "\n".join(parts)

def generate_postgresql(diagram: Diagram) -> str:
    tables, rels = diagram.tables, diagram.relationships
    sorted_tables = topological_sort(tables, rels)
    tmap = {t.id: t for t in tables}
    cmap = {c.id: c for t in tables for c in t.columns}
    parts = ["-- Generated by SketchSQL\n-- Dialect: PostgreSQL\n"]

    for table in sorted_tables:
        col_defs, pks, uniq = [], [], []
        for col in table.columns:
            pgt = pg_type(col.type, col.autoIncrement and col.primaryKey)
            defn = f"  {q(col.name, 'postgresql')} {pgt}"
            if not col.nullable or col.primaryKey:
                defn += " NOT NULL"
            if col.defaultValue:
                defn += f" DEFAULT {fmt_default(col.defaultValue)}"
            col_defs.append(defn)
            if col.primaryKey:
                pks.append(col.name)
            elif col.unique:
                uniq.append(col.name)
        if pks:
            col_defs.append(f"  PRIMARY KEY ({', '.join(q(p, 'postgresql') for p in pks)})")
        for u in uniq:
            col_defs.append(f"  UNIQUE ({q(u, 'postgresql')})")
        parts.append(
            f"CREATE TABLE {q(table.name, 'postgresql')} (\n" +
            ",\n".join(col_defs) +
            "\n);\n"
        )

    # Many-to-many
    for rel in rels:
        if rel.type != "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        jn = f"{src.name}_{tgt.name}"
        sf, tf = f"{src.name}_id", f"{tgt.name}_id"
        spk = next((c for c in src.columns if c.primaryKey), None)
        tpk = next((c for c in tgt.columns if c.primaryKey), None)
        st = pg_type(spk.type if spk else "INT", False)
        tt = pg_type(tpk.type if tpk else "INT", False)
        od, ou = rel.onDelete or "CASCADE", rel.onUpdate or "CASCADE"
        parts.append(
            f"CREATE TABLE {q(jn, 'postgresql')} (\n"
            f"  {q(sf, 'postgresql')} {st} NOT NULL,\n"
            f"  {q(tf, 'postgresql')} {tt} NOT NULL,\n"
            f"  PRIMARY KEY ({q(sf, 'postgresql')}, {q(tf, 'postgresql')}),\n"
            f"  FOREIGN KEY ({q(sf, 'postgresql')}) REFERENCES {q(src.name, 'postgresql')}({q(sc.name, 'postgresql')}) ON DELETE {od} ON UPDATE {ou},\n"
            f"  FOREIGN KEY ({q(tf, 'postgresql')}) REFERENCES {q(tgt.name, 'postgresql')}({q(tc.name, 'postgresql')}) ON DELETE {od} ON UPDATE {ou}\n"
            f");\n"
        )

    # FK constraints
    for rel in rels:
        if rel.type == "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        od, ou = rel.onDelete or "RESTRICT", rel.onUpdate or "RESTRICT"
        fk = f"fk_{src.name}_{sc.name}"
        parts.append(
            f"ALTER TABLE ONLY {q(src.name, 'postgresql')}\n"
            f"  ADD CONSTRAINT {q(fk, 'postgresql')}\n"
            f"  FOREIGN KEY ({q(sc.name, 'postgresql')})\n"
            f"  REFERENCES {q(tgt.name, 'postgresql')}({q(tc.name, 'postgresql')})\n"
            f"  ON DELETE {od} ON UPDATE {ou};\n"
        )

    return "\n".join(parts)

# ─── SQL Parser ─────────────────────────────────────────────────────────────

def split_by_commas(s: str) -> List[str]:
    parts, depth, cur = [], 0, []
    for ch in s:
        if ch == "(":
            depth += 1
            cur.append(ch)
        elif ch == ")":
            depth -= 1
            cur.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur).strip())
    return parts

def parse_sql(sql_string: str, dialect: str = "mysql") -> dict:
    tables, rels, pending_fks = [], [], []
    sql_clean = re.sub(r"--[^\n]*", "", sql_string)
    sql_clean = re.sub(r"/\*.*?\*/", "", sql_clean, flags=re.DOTALL)
    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"\[]?(\w+)[`\"\]]?\s*\((.*?)\)\s*(?:ENGINE\s*=\s*\w+[^;]*)?;",
        re.IGNORECASE | re.DOTALL,
    )
    tname_to_id: Dict[str, str] = {}
    ckey_to_id: Dict[tuple, str] = {}

    for m in pattern.finditer(sql_clean):
        tname, tbody = m.group(1), m.group(2)
        tid = f"t_{uuid4().hex[:8]}"
        tname_to_id[tname.lower()] = tid
        columns, pk_names, fks = [], [], []

        for line in split_by_commas(tbody):
            line = line.strip()
            if not line:
                continue
            # PRIMARY KEY constraint
            pk_m = re.match(r"^PRIMARY\s+KEY\s*\(([^)]+)\)", line, re.IGNORECASE)
            if pk_m:
                pk_names.extend(s.strip().strip("`\"'") for s in pk_m.group(1).split(","))
                continue
            # FOREIGN KEY
            fk_m = re.match(
                r"^(?:CONSTRAINT\s+\w+\s+)?FOREIGN\s+KEY\s*\(([^)]+)\)\s+REFERENCES\s+[`\"\[]?(\w+)[`\"\]]?\s*\(([^)]+)\)"
                r"(?:\s+ON\s+DELETE\s+(CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION|SET\s+DEFAULT))?"
                r"(?:\s+ON\s+UPDATE\s+(CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION|SET\s+DEFAULT))?",
                line, re.IGNORECASE,
            )
            if fk_m:
                fks.append({
                    "src_table": tname,
                    "src_col": fk_m.group(1).strip().strip("`\"'"),
                    "ref_table": fk_m.group(2),
                    "ref_col": fk_m.group(3).strip().strip("`\"'"),
                    "on_delete": (fk_m.group(4) or "RESTRICT").upper(),
                    "on_update": (fk_m.group(5) or "RESTRICT").upper(),
                })
                continue
            # Skip index lines
            if re.match(r"^(?:UNIQUE\s+)?(?:KEY|INDEX)\s+", line, re.IGNORECASE):
                continue
            # Column definition
            col_m = re.match(r"^[`\"\[]?(\w+)[`\"\]]?\s+(\S+(?:\s*\([^)]*\))?)(.*)", line)
            if col_m and not re.match(r"^(PRIMARY|UNIQUE|KEY|INDEX|CONSTRAINT|CHECK)\b", col_m.group(1), re.IGNORECASE):
                cname, raw_t, rest = col_m.group(1), col_m.group(2), col_m.group(3)
                ct = raw_t.upper()
                auto_inc = bool(re.search(r"\bAUTO_INCREMENT\b", rest, re.IGNORECASE))
                if ct in ("SERIAL", "BIGSERIAL"):
                    auto_inc = True
                    ct = "BIGINT" if ct == "BIGSERIAL" else "INT"
                cid = f"c_{uuid4().hex[:8]}"
                col = {
                    "id": cid, "name": cname, "type": ct,
                    "primaryKey": bool(re.search(r"\bPRIMARY\s+KEY\b", rest, re.IGNORECASE)),
                    "autoIncrement": auto_inc,
                    "nullable": not bool(re.search(r"\bNOT\s+NULL\b", rest, re.IGNORECASE)),
                    "unique": bool(re.search(r"\bUNIQUE\b", rest, re.IGNORECASE)),
                    "defaultValue": "",
                }
                dv_m = re.search(r"\bDEFAULT\s+('([^']*)'|\"([^\"]*)\"|(\S+))", rest, re.IGNORECASE)
                if dv_m:
                    col["defaultValue"] = dv_m.group(2) or dv_m.group(3) or dv_m.group(4) or ""
                columns.append(col)
                ckey_to_id[(tname.lower(), cname.lower())] = cid

        for pk in pk_names:
            for c in columns:
                if c["name"].lower() == pk.lower():
                    c["primaryKey"] = True
                    c["nullable"] = False

        pending_fks.extend(fks)
        tables.append({"id": tid, "name": tname, "color": "gray", "columns": columns, "position": {"x": 0, "y": 0}})

    for fk in pending_fks:
        stid = tname_to_id.get(fk["src_table"].lower())
        ttid = tname_to_id.get(fk["ref_table"].lower())
        scid = ckey_to_id.get((fk["src_table"].lower(), fk["src_col"].lower()))
        tcid = ckey_to_id.get((fk["ref_table"].lower(), fk["ref_col"].lower()))
        if stid and ttid and scid and tcid:
            rels.append({
                "id": f"r_{uuid4().hex[:8]}",
                "sourceTableId": stid, "sourceColumnId": scid,
                "targetTableId": ttid, "targetColumnId": tcid,
                "type": "one-to-many",
                "onDelete": fk["on_delete"], "onUpdate": fk["on_update"], "label": "",
            })

    return {"tables": tables, "relationships": rels}

# ─── Routes ─────────────────────────────────────────────────────────────────

@app.get("/api/")
async def health():
    return {"message": "SketchSQL API running", "status": "ok"}

@app.post("/api/generate-sql")
async def generate_sql_route(req: GenerateSqlRequest):
    try:
        sql = generate_mysql(req.diagram) if req.dialect == "mysql" else generate_postgresql(req.diagram)
        return {"sql": sql}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/import-sql")
async def import_sql_route(req: ImportSqlRequest):
    try:
        return {"diagram": parse_sql(req.sql, req.dialect)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/generate-schema")
async def ai_generate_schema(req: AiGenerateSchemaRequest):
    try:
        system_prompt = """You are a database schema designer. The user will describe a system in plain English.
You must respond ONLY with a valid JSON object representing a database schema.
No explanation, no markdown, no backticks. Only raw JSON.

The JSON must follow this exact schema:
{
  "tables": [
    {
      "id": "unique_string_id",
      "name": "TableName",
      "color": "blue|green|purple|orange|red|gray",
      "columns": [
        {
          "id": "unique_col_id",
          "name": "column_name",
          "type": "INT|VARCHAR(255)|TEXT|BOOLEAN|DATE|DATETIME|TIMESTAMP|DECIMAL(10,2)|UUID|BIGINT|FLOAT|JSON",
          "primaryKey": true,
          "autoIncrement": true,
          "nullable": false,
          "unique": false,
          "defaultValue": ""
        }
      ]
    }
  ],
  "relationships": [
    {
      "id": "unique_rel_id",
      "sourceTableId": "id",
      "sourceColumnId": "id",
      "targetTableId": "id",
      "targetColumnId": "id",
      "type": "one-to-one|one-to-many|many-to-many",
      "onDelete": "CASCADE|SET NULL|RESTRICT",
      "onUpdate": "CASCADE|SET NULL|RESTRICT"
    }
  ]
}"""
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Design a database schema for: {req.prompt}"},
            ],
            max_completion_tokens=16384,
        )
        content = resp.choices[0].message.content.strip()
        content = re.sub(r"^```[a-z]*\n?", "", content)
        content = re.sub(r"\n?```$", "", content)
        diagram = json.loads(content)
        return {"diagram": diagram}
    except json.JSONDecodeError as e:
        raise HTTPException(status_code=422, detail=f"AI returned invalid JSON: {e}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/analyze-schema")
async def ai_analyze_schema(req: AiAnalyzeSchemaRequest):
    try:
        schema_json = json.dumps(
            {"tables": [t.dict() for t in req.diagram.tables], "relationships": [r.dict() for r in req.diagram.relationships]},
            indent=2,
        )
        system_prompt = """You are a senior database architect. You will be given a database schema as JSON.
Analyze it and provide:
1. A plain English explanation of what this schema models (2-3 sentences)
2. Normalization issues found (1NF, 2NF, 3NF violations if any) — be specific about which table/column
3. Specific improvement suggestions (missing indexes, redundant columns, naming conventions)
4. A normalized form suggestion if the schema has issues

Format your response in clear sections with headings. Be concise and specific."""
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Analyze this database schema:\n\n{schema_json}"},
            ],
            max_completion_tokens=16384,
        )
        return {"analysis": resp.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/chat")
async def ai_chat(req: AiChatRequest):
    try:
        schema_json = json.dumps(
            {"tables": [t.dict() for t in req.diagram.tables], "relationships": [r.dict() for r in req.diagram.relationships]},
            indent=2,
        )
        system_prompt = f"""You are an expert SQL query writer and database consultant. You have full knowledge of the user's current database schema (provided below as JSON).

When asked to write queries:
- Write clean, well-commented SQL
- Use proper JOINs based on the defined foreign keys
- Always specify the dialect (MySQL or PostgreSQL) in your response
- If the query differs between dialects, show both versions

When asked questions about the schema:
- Reference specific table and column names from the schema
- Be precise and technically accurate

Current dialect: {req.dialect}
Current schema:
{schema_json}"""
        messages = [{"role": "system", "content": system_prompt}]
        messages.extend({"role": m.role, "content": m.content} for m in req.messages)
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=messages,
            max_completion_tokens=16384,
        )
        return {"reply": resp.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ─── Share (Read-Only Snapshot) ─────────────────────────────────────────────

class ShareRequest(BaseModel):
    diagram: Diagram

def _gen_share_id() -> str:
    # ~8-char URL-safe token; 48 bits of entropy
    return secrets.token_urlsafe(6).replace("_", "a").replace("-", "b")

@app.post("/api/share")
async def create_share(req: ShareRequest):
    try:
        for _ in range(5):
            sid = _gen_share_id()
            if not await shares_coll.find_one({"shareId": sid}, {"_id": 1}):
                break
        else:
            raise HTTPException(status_code=500, detail="Failed to allocate share id")
        doc = {
            "shareId": sid,
            "diagram": req.diagram.dict(),
            "createdAt": datetime.now(timezone.utc).isoformat(),
            "views": 0,
        }
        await shares_coll.insert_one(doc)
        return {"shareId": sid}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/share/{share_id}")
async def get_share(share_id: str):
    doc = await shares_coll.find_one({"shareId": share_id}, {"_id": 0})
    if not doc:
        raise HTTPException(status_code=404, detail="Share not found")
    # Best-effort view counter (fire-and-forget)
    try:
        await shares_coll.update_one({"shareId": share_id}, {"$inc": {"views": 1}})
    except Exception:
        pass
    return {
        "shareId": doc.get("shareId"),
        "diagram": doc.get("diagram"),
        "createdAt": doc.get("createdAt"),
        "views": (doc.get("views") or 0) + 1,
    }
