from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import os
import re
import json
import secrets
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4
from dotenv import load_dotenv
from openai import AzureOpenAI
from motor.motor_asyncio import AsyncIOMotorClient
import sqlglot
from sqlglot import exp

# Resolve this file explicitly so the backend loads its settings whether it is
# started from backend/ (as in the README) or from the repository root.
load_dotenv(Path(__file__).with_name(".env"))

app = FastAPI(title="SketchSQL API")

# MongoDB (for shared-diagram snapshots)
_mongo_client = AsyncIOMotorClient(os.environ["MONGO_URL"])
_db = _mongo_client[os.environ["DB_NAME"]]
shares_coll = _db["shares"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Azure OpenAI client (lazy init)
_azure_client = None

def get_client():
    global _azure_client
    if _azure_client is None:
        _azure_client = AzureOpenAI(
            azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT", ""),
            api_key=os.environ.get("AZURE_OPENAI_API_KEY", ""),
            api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-12-01-preview"),
        )
    return _azure_client

DEPLOYMENT = lambda: os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-5.4")

# ─── Pydantic Models ────────────────────────────────────────────────────────

class Column(BaseModel):
    id: str
    name: str
    type: str
    primaryKey: bool = False
    autoIncrement: bool = False
    nullable: bool = True
    unique: bool = False
    defaultValue: str = ""

class Table(BaseModel):
    id: str
    name: str
    color: str = "gray"
    columns: List[Column] = []
    position: Optional[Dict[str, float]] = None

class Relationship(BaseModel):
    id: str
    sourceTableId: str
    sourceColumnId: str
    targetTableId: str
    targetColumnId: str
    type: str = "one-to-many"
    onDelete: str = "RESTRICT"
    onUpdate: str = "RESTRICT"
    label: str = ""

class Diagram(BaseModel):
    id: Optional[str] = None
    name: str = "Untitled"
    dialect: str = "mysql"
    tables: List[Table] = []
    relationships: List[Relationship] = []

class GenerateSqlRequest(BaseModel):
    diagram: Diagram
    dialect: str = "mysql"

class ImportSqlRequest(BaseModel):
    sql: str
    dialect: str = "mysql"

class AiGenerateSchemaRequest(BaseModel):
    prompt: str

class AiAnalyzeSchemaRequest(BaseModel):
    diagram: Diagram
    dialect: str = "mysql"

class ChatMessage(BaseModel):
    role: str
    content: str

class AiChatRequest(BaseModel):
    messages: List[ChatMessage]
    diagram: Diagram
    dialect: str = "mysql"

# ─── SQL Generator ──────────────────────────────────────────────────────────

def q(name: str, dialect: str) -> str:
    return f"`{name}`" if dialect == "mysql" else f'"{name}"'

def pg_type(col_type: str, auto_increment: bool) -> str:
    t = col_type.upper()
    if auto_increment:
        if "BIGINT" in t:
            return "BIGSERIAL"
        if "INT" in t:
            return "SERIAL"
    if t == "DATETIME":
        return "TIMESTAMP"
    if t.startswith("TINYINT"):
        return "BOOLEAN"
    return col_type

def topological_sort(tables: List[Table], relationships: List[Relationship]) -> List[Table]:
    tmap = {t.id: t for t in tables}
    deps: Dict[str, set] = {t.id: set() for t in tables}
    for rel in relationships:
        if rel.type != "many-to-many":
            if rel.sourceTableId in deps and rel.targetTableId in tmap:
                deps[rel.sourceTableId].add(rel.targetTableId)
    visited: set = set()
    result: List[Table] = []

    def dfs(tid: str):
        if tid in visited:
            return
        visited.add(tid)
        for dep in deps.get(tid, set()):
            dfs(dep)
        if tid in tmap:
            result.append(tmap[tid])

    for t in tables:
        dfs(t.id)
    return result

def fmt_default(dv: str) -> str:
    keywords = {"NULL", "CURRENT_TIMESTAMP", "TRUE", "FALSE", "NOW()", "CURRENT_DATE", "CURRENT_TIME"}
    if dv.upper() in keywords or dv.lstrip("-").isdigit():
        return dv
    return f"'{dv}'"

def generate_mysql(diagram: Diagram) -> str:
    tables, rels = diagram.tables, diagram.relationships
    sorted_tables = topological_sort(tables, rels)
    tmap = {t.id: t for t in tables}
    cmap = {c.id: c for t in tables for c in t.columns}
    parts = ["-- Generated by SketchSQL\n-- Dialect: MySQL\n\nSET FOREIGN_KEY_CHECKS=0;\n"]

    for table in sorted_tables:
        col_defs, pks = [], []
        for col in table.columns:
            defn = f"  {q(col.name, 'mysql')} {col.type}"
            if col.autoIncrement and col.primaryKey:
                defn += " AUTO_INCREMENT"
            if not col.nullable or col.primaryKey:
                defn += " NOT NULL"
            if col.unique and not col.primaryKey:
                defn += " UNIQUE"
            if col.defaultValue:
                defn += f" DEFAULT {fmt_default(col.defaultValue)}"
            col_defs.append(defn)
            if col.primaryKey:
                pks.append(col.name)
        if pks:
            col_defs.append(f"  PRIMARY KEY ({', '.join(q(p, 'mysql') for p in pks)})")
        parts.append(
            f"CREATE TABLE {q(table.name, 'mysql')} (\n" +
            ",\n".join(col_defs) +
            "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
        )

    # Many-to-many junction tables
    for rel in rels:
        if rel.type != "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        jn = f"{src.name}_{tgt.name}"
        sf, tf = f"{src.name}_id", f"{tgt.name}_id"
        spk = next((c for c in src.columns if c.primaryKey), None)
        tpk = next((c for c in tgt.columns if c.primaryKey), None)
        st = (spk.type if spk else "INT").split("(")[0]
        tt = (tpk.type if tpk else "INT").split("(")[0]
        od, ou = rel.onDelete or "CASCADE", rel.onUpdate or "CASCADE"
        parts.append(
            f"CREATE TABLE {q(jn, 'mysql')} (\n"
            f"  {q(sf, 'mysql')} {st} NOT NULL,\n"
            f"  {q(tf, 'mysql')} {tt} NOT NULL,\n"
            f"  PRIMARY KEY ({q(sf, 'mysql')}, {q(tf, 'mysql')}),\n"
            f"  FOREIGN KEY ({q(sf, 'mysql')}) REFERENCES {q(src.name, 'mysql')}({q(sc.name, 'mysql')}) ON DELETE {od} ON UPDATE {ou},\n"
            f"  FOREIGN KEY ({q(tf, 'mysql')}) REFERENCES {q(tgt.name, 'mysql')}({q(tc.name, 'mysql')}) ON DELETE {od} ON UPDATE {ou}\n"
            f") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
        )

    # FK constraints
    for rel in rels:
        if rel.type == "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        od, ou = rel.onDelete or "RESTRICT", rel.onUpdate or "RESTRICT"
        fk = f"fk_{src.name}_{sc.name}"
        parts.append(
            f"ALTER TABLE {q(src.name, 'mysql')}\n"
            f"  ADD CONSTRAINT {q(fk, 'mysql')}\n"
            f"  FOREIGN KEY ({q(sc.name, 'mysql')})\n"
            f"  REFERENCES {q(tgt.name, 'mysql')}({q(tc.name, 'mysql')})\n"
            f"  ON DELETE {od} ON UPDATE {ou};\n"
        )

    parts.append("\nSET FOREIGN_KEY_CHECKS=1;")
    return "\n".join(parts)

def generate_postgresql(diagram: Diagram) -> str:
    tables, rels = diagram.tables, diagram.relationships
    sorted_tables = topological_sort(tables, rels)
    tmap = {t.id: t for t in tables}
    cmap = {c.id: c for t in tables for c in t.columns}
    parts = ["-- Generated by SketchSQL\n-- Dialect: PostgreSQL\n"]

    for table in sorted_tables:
        col_defs, pks, uniq = [], [], []
        for col in table.columns:
            pgt = pg_type(col.type, col.autoIncrement and col.primaryKey)
            defn = f"  {q(col.name, 'postgresql')} {pgt}"
            if not col.nullable or col.primaryKey:
                defn += " NOT NULL"
            if col.defaultValue:
                defn += f" DEFAULT {fmt_default(col.defaultValue)}"
            col_defs.append(defn)
            if col.primaryKey:
                pks.append(col.name)
            elif col.unique:
                uniq.append(col.name)
        if pks:
            col_defs.append(f"  PRIMARY KEY ({', '.join(q(p, 'postgresql') for p in pks)})")
        for u in uniq:
            col_defs.append(f"  UNIQUE ({q(u, 'postgresql')})")
        parts.append(
            f"CREATE TABLE {q(table.name, 'postgresql')} (\n" +
            ",\n".join(col_defs) +
            "\n);\n"
        )

    # Many-to-many
    for rel in rels:
        if rel.type != "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        jn = f"{src.name}_{tgt.name}"
        sf, tf = f"{src.name}_id", f"{tgt.name}_id"
        spk = next((c for c in src.columns if c.primaryKey), None)
        tpk = next((c for c in tgt.columns if c.primaryKey), None)
        st = pg_type(spk.type if spk else "INT", False)
        tt = pg_type(tpk.type if tpk else "INT", False)
        od, ou = rel.onDelete or "CASCADE", rel.onUpdate or "CASCADE"
        parts.append(
            f"CREATE TABLE {q(jn, 'postgresql')} (\n"
            f"  {q(sf, 'postgresql')} {st} NOT NULL,\n"
            f"  {q(tf, 'postgresql')} {tt} NOT NULL,\n"
            f"  PRIMARY KEY ({q(sf, 'postgresql')}, {q(tf, 'postgresql')}),\n"
            f"  FOREIGN KEY ({q(sf, 'postgresql')}) REFERENCES {q(src.name, 'postgresql')}({q(sc.name, 'postgresql')}) ON DELETE {od} ON UPDATE {ou},\n"
            f"  FOREIGN KEY ({q(tf, 'postgresql')}) REFERENCES {q(tgt.name, 'postgresql')}({q(tc.name, 'postgresql')}) ON DELETE {od} ON UPDATE {ou}\n"
            f");\n"
        )

    # FK constraints
    for rel in rels:
        if rel.type == "many-to-many":
            continue
        src, tgt = tmap.get(rel.sourceTableId), tmap.get(rel.targetTableId)
        sc, tc = cmap.get(rel.sourceColumnId), cmap.get(rel.targetColumnId)
        if not (src and tgt and sc and tc):
            continue
        od, ou = rel.onDelete or "RESTRICT", rel.onUpdate or "RESTRICT"
        fk = f"fk_{src.name}_{sc.name}"
        parts.append(
            f"ALTER TABLE ONLY {q(src.name, 'postgresql')}\n"
            f"  ADD CONSTRAINT {q(fk, 'postgresql')}\n"
            f"  FOREIGN KEY ({q(sc.name, 'postgresql')})\n"
            f"  REFERENCES {q(tgt.name, 'postgresql')}({q(tc.name, 'postgresql')})\n"
            f"  ON DELETE {od} ON UPDATE {ou};\n"
        )

    return "\n".join(parts)

# ─── SQL Parser ─────────────────────────────────────────────────────────────

def parse_sql(sql_string: str, dialect: str = "mysql") -> dict:
    tables = []
    rels = []
    
    primary_dialect = "postgres" if dialect.lower() in ("postgresql", "postgres") else "mysql"
    candidate_dialects = [primary_dialect, "postgres", "mysql", "sqlite", None]
    
    seen = set()
    dialects_to_try = [d for d in candidate_dialects if not (d in seen or seen.add(d))]

    parsed_statements = []
    detected_dialect = "mysql"
    for d in dialects_to_try:
        try:
            stmts = [s for s in sqlglot.parse(sql_string, read=d) if s is not None]
            table_stmts = [s for s in stmts if isinstance(s, exp.Create) and s.kind == "TABLE"]
            if table_stmts:
                parsed_statements = stmts
                detected_dialect = "postgresql" if d == "postgres" else (d or "mysql")
                break
        except Exception:
            continue

    tname_to_id: Dict[str, str] = {}
    ckey_to_id: Dict[tuple, str] = {}
    table_pks: Dict[str, List[str]] = {}
    pending_fks: List[dict] = []

    def get_name(expr) -> str:
        if not expr:
            return ""
        if isinstance(expr, exp.Schema):
            return get_name(expr.this)
        if isinstance(expr, (exp.Table, exp.Identifier, exp.Column)):
            return expr.name
        if hasattr(expr, "this"):
            return get_name(expr.this)
        return str(expr)

    # Pass 1: Parse CREATE TABLE statements
    for stmt in parsed_statements:
        if not (isinstance(stmt, exp.Create) and stmt.kind == "TABLE"):
            continue

        schema_expr = stmt.this
        if not isinstance(schema_expr, exp.Schema):
            tname = get_name(schema_expr)
            tid = f"t_{uuid4().hex[:8]}"
            tname_to_id[tname.lower()] = tid
            tables.append({"id": tid, "name": tname, "color": "gray", "columns": [], "position": {"x": 0, "y": 0}})
            continue

        tname = get_name(schema_expr.this)
        tid = f"t_{uuid4().hex[:8]}"
        tname_to_id[tname.lower()] = tid

        columns = []
        pk_names = []
        fks = []

        for e in schema_expr.expressions:
            if isinstance(e, exp.ColumnDef):
                cname = get_name(e.this)
                raw_type = e.kind.sql() if e.kind else "VARCHAR"
                ct = raw_type.upper()

                primary_key = False
                auto_increment = False
                nullable = True
                unique = False
                default_val = ""

                if ct in ("SERIAL", "BIGSERIAL"):
                    auto_increment = True
                    ct = "BIGINT" if ct == "BIGSERIAL" else "INT"

                for constraint in e.constraints:
                    kind = constraint.kind
                    if isinstance(kind, exp.PrimaryKeyColumnConstraint):
                        primary_key = True
                        nullable = False
                    elif isinstance(kind, exp.AutoIncrementColumnConstraint):
                        auto_increment = True
                    elif isinstance(kind, exp.NotNullColumnConstraint):
                        nullable = False
                    elif isinstance(kind, exp.UniqueColumnConstraint):
                        unique = True
                    elif isinstance(kind, exp.DefaultColumnConstraint):
                        dv_expr = constraint.expression or kind.this
                        if dv_expr:
                            default_val = dv_expr.sql().strip("'\"")
                    elif isinstance(kind, exp.Reference):
                        ref_schema = kind.this
                        ref_tname = get_name(ref_schema)
                        ref_col = ""
                        if isinstance(ref_schema, exp.Schema) and ref_schema.expressions:
                            ref_col = get_name(ref_schema.expressions[0])

                        on_delete = "RESTRICT"
                        on_update = "RESTRICT"
                        for opt in (kind.args.get("options") or []):
                            opt_str = str(opt).upper()
                            if "ON DELETE" in opt_str:
                                on_delete = opt_str.replace("ON DELETE", "").strip()
                            elif "ON UPDATE" in opt_str:
                                on_update = opt_str.replace("ON UPDATE", "").strip()

                        fks.append({
                            "src_table": tname,
                            "src_col": cname,
                            "ref_table": ref_tname,
                            "ref_col": ref_col,
                            "on_delete": on_delete,
                            "on_update": on_update,
                        })

                cid = f"c_{uuid4().hex[:8]}"
                col = {
                    "id": cid,
                    "name": cname,
                    "type": ct,
                    "primaryKey": primary_key,
                    "autoIncrement": auto_increment,
                    "nullable": nullable,
                    "unique": unique,
                    "defaultValue": default_val,
                }
                columns.append(col)
                ckey_to_id[(tname.lower(), cname.lower())] = cid
                if primary_key:
                    pk_names.append(cname)

            elif isinstance(e, exp.PrimaryKey):
                for pk_col in e.expressions:
                    pk_names.append(get_name(pk_col))

            elif isinstance(e, exp.ForeignKey):
                src_cols = [get_name(c) for c in e.expressions]
                ref_obj = e.args.get("reference")
                if ref_obj:
                    ref_tname = get_name(ref_obj.this)
                    ref_cols = []
                    if isinstance(ref_obj.this, exp.Schema) and ref_obj.this.expressions:
                        ref_cols = [get_name(c) for c in ref_obj.this.expressions]

                    on_delete = "RESTRICT"
                    on_update = "RESTRICT"
                    for opt in (ref_obj.args.get("options") or []):
                        opt_str = str(opt).upper()
                        if "ON DELETE" in opt_str:
                            on_delete = opt_str.replace("ON DELETE", "").strip()
                        elif "ON UPDATE" in opt_str:
                            on_update = opt_str.replace("ON UPDATE", "").strip()

                    for i, scol in enumerate(src_cols):
                        rcol = ref_cols[i] if i < len(ref_cols) else ""
                        fks.append({
                            "src_table": tname,
                            "src_col": scol,
                            "ref_table": ref_tname,
                            "ref_col": rcol,
                            "on_delete": on_delete,
                            "on_update": on_update,
                        })

        for col in columns:
            if col["name"].lower() in [p.lower() for p in pk_names]:
                col["primaryKey"] = True
                col["nullable"] = False

        table_pks[tname.lower()] = [c["name"].lower() for c in columns if c["primaryKey"]] or [p.lower() for p in pk_names] or ["id"]
        pending_fks.extend(fks)
        tables.append({"id": tid, "name": tname, "color": "gray", "columns": columns, "position": {"x": 0, "y": 0}})

    # Pass 2: Parse ALTER TABLE statements
    for stmt in parsed_statements:
        if isinstance(stmt, exp.Alter):
            tname = get_name(stmt.this)
            actions = stmt.args.get("actions") or []
            for act in actions:
                fk_node = None
                if isinstance(act, exp.Add):
                    this_obj = act.this
                    if isinstance(this_obj, exp.ForeignKey):
                        fk_node = this_obj
                    elif isinstance(this_obj, exp.Constraint):
                        for sub in this_obj.expressions:
                            if isinstance(sub, exp.ForeignKey):
                                fk_node = sub

                if fk_node:
                    src_cols = [get_name(c) for c in fk_node.expressions]
                    ref_obj = fk_node.args.get("reference")
                    if ref_obj:
                        ref_tname = get_name(ref_obj.this)
                        ref_cols = []
                        if isinstance(ref_obj.this, exp.Schema) and ref_obj.this.expressions:
                            ref_cols = [get_name(c) for c in ref_obj.this.expressions]

                        on_delete = "RESTRICT"
                        on_update = "RESTRICT"
                        for opt in (ref_obj.args.get("options") or []):
                            opt_str = str(opt).upper()
                            if "ON DELETE" in opt_str:
                                on_delete = opt_str.replace("ON DELETE", "").strip()
                            elif "ON UPDATE" in opt_str:
                                on_update = opt_str.replace("ON UPDATE", "").strip()

                        for i, scol in enumerate(src_cols):
                            rcol = ref_cols[i] if i < len(ref_cols) else ""
                            pending_fks.append({
                                "src_table": tname,
                                "src_col": scol,
                                "ref_table": ref_tname,
                                "ref_col": rcol,
                                "on_delete": on_delete,
                                "on_update": on_update,
                            })

    # Resolve pending foreign keys to relationships
    for fk in pending_fks:
        stid = tname_to_id.get(fk["src_table"].lower())
        ttid = tname_to_id.get(fk["ref_table"].lower())
        scid = ckey_to_id.get((fk["src_table"].lower(), fk["src_col"].lower()))

        ref_cname = fk["ref_col"].lower()
        if not ref_cname:
            target_pks = table_pks.get(fk["ref_table"].lower(), ["id"])
            ref_cname = target_pks[0] if target_pks else "id"

        tcid = ckey_to_id.get((fk["ref_table"].lower(), ref_cname))

        if stid and ttid and scid and tcid:
            rels.append({
                "id": f"r_{uuid4().hex[:8]}",
                "sourceTableId": stid,
                "sourceColumnId": scid,
                "targetTableId": ttid,
                "targetColumnId": tcid,
                "type": "one-to-many",
                "onDelete": fk["on_delete"],
                "onUpdate": fk["on_update"],
                "label": "",
            })

    return {"tables": tables, "relationships": rels, "dialect": detected_dialect}

# ─── Routes ─────────────────────────────────────────────────────────────────

@app.get("/api/")
async def health():
    return {"message": "SketchSQL API running", "status": "ok"}

@app.post("/api/generate-sql")
async def generate_sql_route(req: GenerateSqlRequest):
    try:
        sql = generate_mysql(req.diagram) if req.dialect == "mysql" else generate_postgresql(req.diagram)
        return {"sql": sql}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/import-sql")
async def import_sql_route(req: ImportSqlRequest):
    try:
        return {"diagram": parse_sql(req.sql, req.dialect)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/generate-schema")
async def ai_generate_schema(req: AiGenerateSchemaRequest):
    try:
        system_prompt = """You are a database schema designer. The user will describe a system in plain English.
You must respond ONLY with a valid JSON object representing a database schema.
No explanation, no markdown, no backticks. Only raw JSON.

The JSON must follow this exact schema:
{
  "tables": [
    {
      "id": "unique_string_id",
      "name": "TableName",
      "color": "blue|green|purple|orange|red|gray",
      "columns": [
        {
          "id": "unique_col_id",
          "name": "column_name",
          "type": "INT|VARCHAR(255)|TEXT|BOOLEAN|DATE|DATETIME|TIMESTAMP|DECIMAL(10,2)|UUID|BIGINT|FLOAT|JSON",
          "primaryKey": true,
          "autoIncrement": true,
          "nullable": false,
          "unique": false,
          "defaultValue": ""
        }
      ]
    }
  ],
  "relationships": [
    {
      "id": "unique_rel_id",
      "sourceTableId": "id",
      "sourceColumnId": "id",
      "targetTableId": "id",
      "targetColumnId": "id",
      "type": "one-to-one|one-to-many|many-to-many",
      "onDelete": "CASCADE|SET NULL|RESTRICT",
      "onUpdate": "CASCADE|SET NULL|RESTRICT"
    }
  ]
}"""
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Design a database schema for: {req.prompt}"},
            ],
            max_completion_tokens=16384,
        )
        content = resp.choices[0].message.content.strip()
        content = re.sub(r"^```[a-z]*\n?", "", content)
        content = re.sub(r"\n?```$", "", content)
        diagram = json.loads(content)
        return {"diagram": diagram}
    except json.JSONDecodeError as e:
        raise HTTPException(status_code=422, detail=f"AI returned invalid JSON: {e}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/analyze-schema")
async def ai_analyze_schema(req: AiAnalyzeSchemaRequest):
    try:
        schema_json = json.dumps(
            {"tables": [t.dict() for t in req.diagram.tables], "relationships": [r.dict() for r in req.diagram.relationships]},
            indent=2,
        )
        system_prompt = """You are a senior database architect. You will be given a database schema as JSON.
Analyze it and provide:
1. A plain English explanation of what this schema models (2-3 sentences)
2. Normalization issues found (1NF, 2NF, 3NF violations if any) — be specific about which table/column
3. Specific improvement suggestions (missing indexes, redundant columns, naming conventions)
4. A normalized form suggestion if the schema has issues

Format your response in clear sections with headings. Be concise and specific."""
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Analyze this database schema:\n\n{schema_json}"},
            ],
            max_completion_tokens=16384,
        )
        return {"analysis": resp.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai/chat")
async def ai_chat(req: AiChatRequest):
    try:
        schema_json = json.dumps(
            {"tables": [t.dict() for t in req.diagram.tables], "relationships": [r.dict() for r in req.diagram.relationships]},
            indent=2,
        )
        system_prompt = f"""You are an expert SQL query writer and database consultant. You have full knowledge of the user's current database schema (provided below as JSON).

When asked to write queries:
- Write clean, well-commented SQL
- Use proper JOINs based on the defined foreign keys
- Always specify the dialect (MySQL or PostgreSQL) in your response
- If the query differs between dialects, show both versions

When asked questions about the schema:
- Reference specific table and column names from the schema
- Be precise and technically accurate

Current dialect: {req.dialect}
Current schema:
{schema_json}"""
        messages = [{"role": "system", "content": system_prompt}]
        messages.extend({"role": m.role, "content": m.content} for m in req.messages)
        resp = get_client().chat.completions.create(
            model=DEPLOYMENT(),
            messages=messages,
            max_completion_tokens=16384,
        )
        return {"reply": resp.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ─── Share (Read-Only Snapshot) ─────────────────────────────────────────────

class ShareRequest(BaseModel):
    diagram: Diagram

def _gen_share_id() -> str:
    # ~8-char URL-safe token; 48 bits of entropy
    return secrets.token_urlsafe(6).replace("_", "a").replace("-", "b")

@app.post("/api/share")
async def create_share(req: ShareRequest):
    try:
        for _ in range(5):
            sid = _gen_share_id()
            if not await shares_coll.find_one({"shareId": sid}, {"_id": 1}):
                break
        else:
            raise HTTPException(status_code=500, detail="Failed to allocate share id")
        doc = {
            "shareId": sid,
            "diagram": req.diagram.dict(),
            "createdAt": datetime.now(timezone.utc).isoformat(),
            "views": 0,
        }
        await shares_coll.insert_one(doc)
        return {"shareId": sid}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/share/{share_id}")
async def get_share(share_id: str):
    doc = await shares_coll.find_one({"shareId": share_id}, {"_id": 0})
    if not doc:
        raise HTTPException(status_code=404, detail="Share not found")
    # Best-effort view counter (fire-and-forget)
    try:
        await shares_coll.update_one({"shareId": share_id}, {"$inc": {"views": 1}})
    except Exception:
        pass
    return {
        "shareId": doc.get("shareId"),
        "diagram": doc.get("diagram"),
        "createdAt": doc.get("createdAt"),
        "views": (doc.get("views") or 0) + 1,
    }
