// ORM Code Generator — Django, Prisma, SQLAlchemy

function extractType(sqlType) {
  const m = sqlType.match(/^([A-Z]+)\(([^)]+)\)/i);
  return {
    base: (m ? m[1] : sqlType).toUpperCase(),
    params: m ? m[2].split(',').map((s) => s.trim()) : [],
  };
}

function toPascal(str) {
  return str.replace(/[_\s]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, (c) => c.toUpperCase());
}

// ─── Django ───────────────────────────────────────────────────────────────

function djangoField(col) {
  const { base, params } = extractType(col.type);
  const nu = col.nullable && !col.primaryKey ? ', null=True, blank=True' : '';
  const uq = col.unique && !col.primaryKey ? ', unique=True' : '';
  const dv = col.defaultValue && !col.defaultValue.includes('CURRENT') ? `, default='${col.defaultValue}'` : '';
  switch (base) {
    case 'INT': return `models.IntegerField(${nu}${uq}${dv})`;
    case 'BIGINT': return `models.BigIntegerField(${nu}${uq}${dv})`;
    case 'SMALLINT': case 'TINYINT': return `models.SmallIntegerField(${nu}${uq}${dv})`;
    case 'VARCHAR': return `models.CharField(max_length=${params[0] || 255}${nu}${uq}${dv})`;
    case 'TEXT': return `models.TextField(${nu}${uq}${dv})`;
    case 'BOOLEAN': return `models.BooleanField(default=False${uq})`;
    case 'DATE': return `models.DateField(${nu}${dv})`;
    case 'DATETIME': case 'TIMESTAMP':
      return col.defaultValue?.includes('CURRENT') ? 'models.DateTimeField(auto_now_add=True)' : `models.DateTimeField(${nu}${dv})`;
    case 'DECIMAL': return `models.DecimalField(max_digits=${params[0] || 10}, decimal_places=${params[1] || 2}${nu}${dv})`;
    case 'UUID': return `models.UUIDField(${col.primaryKey ? 'primary_key=True, default=uuid.uuid4, editable=False' : `${nu}${uq}`})`;
    case 'FLOAT': return `models.FloatField(${nu}${dv})`;
    case 'JSON': return `models.JSONField(${nu}${dv})`;
    default: return `models.TextField(${nu}${uq}${dv})`;
  }
}

function djangoOnDelete(a) {
  const m = { CASCADE: 'models.CASCADE', 'SET NULL': 'models.SET_NULL', RESTRICT: 'models.RESTRICT', 'NO ACTION': 'models.RESTRICT' };
  return m[a] || 'models.RESTRICT';
}

export function generateDjango(diagram) {
  const { tables = [], relationships = [] } = diagram;
  if (!tables.length) return '# No tables defined\n# Add tables to the canvas to generate Django models';
  const tmap = Object.fromEntries(tables.map((t) => [t.id, t]));
  const cmap = {};
  tables.forEach((t) => t.columns?.forEach((c) => { cmap[c.id] = c; }));
  const fkRels = (tid) => relationships.filter((r) => r.type !== 'many-to-many' && r.sourceTableId === tid);
  const m2mRels = (tid) => relationships.filter((r) => r.type === 'many-to-many' && r.sourceTableId === tid);
  const fkColIds = (tid) => new Set(fkRels(tid).map((r) => r.sourceColumnId));

  const lines = [
    '# Generated by SketchSQL',
    '# Django Models\n',
    'from django.db import models',
    'import uuid\n\n',
  ];

  for (const table of tables) {
    const model = toPascal(table.name);
    const fkCols = fkColIds(table.id);
    const fields = [];

    for (const col of table.columns || []) {
      if (col.primaryKey && col.autoIncrement && col.name === 'id') continue; // Django auto-id
      if (fkCols.has(col.id)) continue;
      fields.push(`    ${col.name} = ${djangoField(col)}`);
    }

    for (const rel of fkRels(table.id)) {
      const srcCol = cmap[rel.sourceColumnId];
      const tgt = tmap[rel.targetTableId];
      if (!srcCol || !tgt) continue;
      const fname = srcCol.name.endsWith('_id') ? srcCol.name.slice(0, -3) : srcCol.name;
      const RelClass = rel.type === 'one-to-one' ? 'OneToOneField' : 'ForeignKey';
      const nu = srcCol.nullable ? ', null=True, blank=True' : '';
      fields.push(`    ${fname} = models.${RelClass}('${toPascal(tgt.name)}', on_delete=${djangoOnDelete(rel.onDelete)}${nu})`);
    }

    for (const rel of m2mRels(table.id)) {
      const tgt = tmap[rel.targetTableId];
      if (!tgt) continue;
      fields.push(`    ${tgt.name.toLowerCase()}s = models.ManyToManyField('${toPascal(tgt.name)}')`);
    }

    if (!fields.length) fields.push('    pass');
    lines.push(`class ${model}(models.Model):`);
    lines.push(...fields);
    lines.push(`\n    class Meta:`);
    lines.push(`        db_table = '${table.name}'`);
    lines.push('\n');
  }

  return lines.join('\n');
}

// ─── Prisma ───────────────────────────────────────────────────────────────

function prismaType(col) {
  const { base } = extractType(col.type);
  const m = { INT: 'Int', BIGINT: 'BigInt', SMALLINT: 'Int', TINYINT: 'Int', VARCHAR: 'String', TEXT: 'String', BOOLEAN: 'Boolean', DATE: 'DateTime', DATETIME: 'DateTime', TIMESTAMP: 'DateTime', DECIMAL: 'Decimal', UUID: 'String', FLOAT: 'Float', JSON: 'Json' };
  return m[base] || 'String';
}

export function generatePrisma(diagram) {
  const { tables = [], relationships = [] } = diagram;
  if (!tables.length) return '// No tables defined\n// Add tables to the canvas to generate Prisma schema';
  const tmap = Object.fromEntries(tables.map((t) => [t.id, t]));
  const cmap = {};
  tables.forEach((t) => t.columns?.forEach((c) => { cmap[c.id] = c; }));

  const lines = [
    '// Generated by SketchSQL',
    '// Prisma Schema\n',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}\n',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}\n',
  ];

  for (const table of tables) {
    const model = toPascal(table.name);
    const fkRelsForTable = relationships.filter((r) => r.type !== 'many-to-many' && r.sourceTableId === table.id);
    const m2mRelsForTable = relationships.filter((r) => r.type === 'many-to-many' && r.sourceTableId === table.id);
    const fkColIds = new Set(fkRelsForTable.map((r) => r.sourceColumnId));
    const backRels = relationships.filter((r) => r.type !== 'many-to-many' && r.targetTableId === table.id);

    const fields = [];

    for (const col of table.columns || []) {
      if (fkColIds.has(col.id)) continue;
      const pt = prismaType(col);
      const opt = col.nullable && !col.primaryKey ? '?' : '';
      const attrs = [];
      if (col.primaryKey) attrs.push('@id');
      if (col.autoIncrement) attrs.push('@default(autoincrement())');
      else if (col.defaultValue?.includes('CURRENT')) attrs.push('@default(now())');
      else if (col.defaultValue) attrs.push(`@default(${col.defaultValue})`);
      if (col.unique && !col.primaryKey) attrs.push('@unique');
      fields.push(`  ${col.name}  ${pt}${opt}  ${attrs.join(' ')}`);
    }

    for (const rel of fkRelsForTable) {
      const srcCol = cmap[rel.sourceColumnId];
      const tgt = tmap[rel.targetTableId];
      const tgtCol = cmap[rel.targetColumnId];
      if (!srcCol || !tgt || !tgtCol) continue;
      const pt = prismaType(srcCol);
      const opt = srcCol.nullable ? '?' : '';
      const relField = tgt.name.toLowerCase();
      const tgtModel = toPascal(tgt.name);
      fields.push(`  ${srcCol.name}  ${pt}${opt}`);
      fields.push(`  ${relField}  ${tgtModel}${opt}  @relation(fields: [${srcCol.name}], references: [${tgtCol.name}])`);
    }

    for (const rel of backRels) {
      const src = tmap[rel.sourceTableId];
      if (!src) continue;
      const srcModel = toPascal(src.name);
      const fname = src.name.toLowerCase() + (rel.type !== 'one-to-one' ? 's' : '');
      fields.push(`  ${fname}  ${rel.type === 'one-to-one' ? `${srcModel}?` : `${srcModel}[]`}`);
    }

    for (const rel of m2mRelsForTable) {
      const tgt = tmap[rel.targetTableId];
      if (!tgt) continue;
      fields.push(`  ${tgt.name.toLowerCase()}s  ${toPascal(tgt.name)}[]`);
    }

    lines.push(`model ${model} {`);
    lines.push(...fields);
    lines.push(`\n  @@map("${table.name}")`);
    lines.push('}\n');
  }

  return lines.join('\n');
}

// ─── SQLAlchemy ───────────────────────────────────────────────────────────

function saType(sqlType) {
  const { base, params } = extractType(sqlType);
  const m = { INT: 'Integer', BIGINT: 'BigInteger', SMALLINT: 'SmallInteger', TINYINT: 'SmallInteger', VARCHAR: `String(${params[0] || 255})`, TEXT: 'Text', BOOLEAN: 'Boolean', DATE: 'Date', DATETIME: 'DateTime', TIMESTAMP: 'DateTime', DECIMAL: `Numeric(${params.join(', ') || '10, 2'})`, UUID: 'UUID(as_uuid=True)', FLOAT: 'Float', JSON: 'JSON' };
  return m[base] || 'String';
}

export function generateSQLAlchemy(diagram) {
  const { tables = [], relationships = [] } = diagram;
  if (!tables.length) return '# No tables defined\n# Add tables to the canvas to generate SQLAlchemy models';
  const tmap = Object.fromEntries(tables.map((t) => [t.id, t]));
  const cmap = {};
  tables.forEach((t) => t.columns?.forEach((c) => { cmap[c.id] = c; }));

  const lines = [
    '# Generated by SketchSQL',
    '# SQLAlchemy Models\n',
    'from sqlalchemy import Column, Integer, BigInteger, SmallInteger, String, Text,',
    '    Boolean, Float, Numeric, Date, DateTime, JSON, ForeignKey',
    'from sqlalchemy.dialects.postgresql import UUID',
    'from sqlalchemy.orm import relationship, DeclarativeBase',
    'import uuid\n\n',
    'class Base(DeclarativeBase):',
    '    pass\n\n',
  ];

  for (const table of tables) {
    const model = toPascal(table.name);
    const fkRelsForTable = relationships.filter((r) => r.type !== 'many-to-many' && r.sourceTableId === table.id);
    const fkColIds = new Set(fkRelsForTable.map((r) => r.sourceColumnId));

    const fields = [`    __tablename__ = '${table.name}'\n`];

    for (const col of table.columns || []) {
      if (fkColIds.has(col.id)) continue;
      const t = saType(col.type);
      const attrs = [];
      if (col.primaryKey) attrs.push('primary_key=True');
      if (col.autoIncrement) attrs.push('autoincrement=True');
      if (!col.nullable && !col.primaryKey) attrs.push('nullable=False');
      if (col.unique && !col.primaryKey) attrs.push('unique=True');
      if (col.defaultValue && !col.defaultValue.includes('CURRENT')) attrs.push(`default='${col.defaultValue}'`);
      const attrsStr = attrs.length ? ', ' + attrs.join(', ') : '';
      fields.push(`    ${col.name} = Column(${t}${attrsStr})`);
    }

    for (const rel of fkRelsForTable) {
      const srcCol = cmap[rel.sourceColumnId];
      const tgt = tmap[rel.targetTableId];
      const tgtPK = tgt?.columns.find((c) => c.primaryKey);
      if (!srcCol || !tgt) continue;
      const t = saType(srcCol.type);
      const nu = srcCol.nullable ? '' : ', nullable=False';
      const onDel = rel.onDelete === 'CASCADE' ? ', ondelete="CASCADE"' : '';
      fields.push(`    ${srcCol.name} = Column(${t}, ForeignKey('${tgt.name}.${tgtPK?.name || 'id'}'${onDel})${nu})`);
      const relField = tgt.name.toLowerCase();
      fields.push(`    ${relField} = relationship('${toPascal(tgt.name)}', back_populates='${table.name.toLowerCase()}s')`);
    }

    lines.push(`class ${model}(Base):`);
    lines.push(...fields);
    lines.push('\n');
  }

  return lines.join('\n');
}
