// Client-side SQL generation (instant, no network)

const q = (name, dialect) => dialect === 'mysql' ? `\`${name}\`` : `"${name}"`;

const pgType = (type, autoInc) => {
  if (autoInc) {
    if (/BIGINT/i.test(type)) return 'BIGSERIAL';
    if (/INT/i.test(type)) return 'SERIAL';
  }
  if (/^DATETIME$/i.test(type)) return 'TIMESTAMP';
  if (/^TINYINT/i.test(type)) return 'BOOLEAN';
  return type;
};

const fmtDefault = (dv) => {
  const kw = ['NULL', 'CURRENT_TIMESTAMP', 'TRUE', 'FALSE', 'NOW()', 'CURRENT_DATE'];
  if (kw.includes(dv.toUpperCase()) || /^-?\d+(\.\d+)?$/.test(dv)) return dv;
  return `'${dv}'`;
};

function topoSort(tables, relationships) {
  const tmap = Object.fromEntries(tables.map(t => [t.id, t]));
  const deps = Object.fromEntries(tables.map(t => [t.id, new Set()]));
  for (const r of relationships) {
    if (r.type !== 'many-to-many' && deps[r.sourceTableId]) {
      deps[r.sourceTableId].add(r.targetTableId);
    }
  }
  const visited = new Set(), result = [];
  const dfs = (id) => {
    if (visited.has(id)) return;
    visited.add(id);
    for (const dep of (deps[id] || [])) dfs(dep);
    if (tmap[id]) result.push(tmap[id]);
  };
  tables.forEach(t => dfs(t.id));
  return result;
}

export function generateSQL(diagram, dialect = 'mysql') {
  if (!diagram || !diagram.tables || diagram.tables.length === 0) {
    return `-- No tables defined\n-- Add tables to the canvas to generate SQL`;
  }

  const { tables, relationships = [] } = diagram;
  const sorted = topoSort(tables, relationships);
  const tmap = Object.fromEntries(tables.map(t => [t.id, t]));
  const cmap = {};
  tables.forEach(t => t.columns?.forEach(c => { cmap[c.id] = c; }));

  const parts = dialect === 'mysql'
    ? ['-- Generated by SketchSQL\n-- Dialect: MySQL\n\nSET FOREIGN_KEY_CHECKS=0;\n']
    : ['-- Generated by SketchSQL\n-- Dialect: PostgreSQL\n'];

  for (const table of sorted) {
    if (!table.columns?.length) continue;
    const colDefs = [], pks = [], uniq = [];

    for (const col of table.columns) {
      let colType = dialect === 'postgresql' ? pgType(col.type, col.autoIncrement && col.primaryKey) : col.type;
      let defn = `  ${q(col.name, dialect)} ${colType}`;
      if (dialect === 'mysql' && col.autoIncrement && col.primaryKey) defn += ' AUTO_INCREMENT';
      if (!col.nullable || col.primaryKey) defn += ' NOT NULL';
      if (col.unique && !col.primaryKey) {
        if (dialect === 'mysql') defn += ' UNIQUE';
        else uniq.push(col.name);
      }
      if (col.defaultValue) defn += ` DEFAULT ${fmtDefault(col.defaultValue)}`;
      colDefs.push(defn);
      if (col.primaryKey) pks.push(col.name);
    }
    if (pks.length) colDefs.push(`  PRIMARY KEY (${pks.map(p => q(p, dialect)).join(', ')})`);
    if (dialect === 'postgresql') uniq.forEach(u => colDefs.push(`  UNIQUE (${q(u, dialect)})`));

    const ending = dialect === 'mysql' ? ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n' : ');\n';
    parts.push(`CREATE TABLE ${q(table.name, dialect)} (\n${colDefs.join(',\n')}\n${ending}`);
  }

  // M:N junction tables
  for (const rel of relationships) {
    if (rel.type !== 'many-to-many') continue;
    const src = tmap[rel.sourceTableId], tgt = tmap[rel.targetTableId];
    const sc = cmap[rel.sourceColumnId], tc = cmap[rel.targetColumnId];
    if (!src || !tgt || !sc || !tc) continue;
    const jn = `${src.name}_${tgt.name}`;
    const sf = `${src.name}_id`, tf = `${tgt.name}_id`;
    const spk = src.columns.find(c => c.primaryKey);
    const tpk = tgt.columns.find(c => c.primaryKey);
    const st = pgType((spk?.type || 'INT').split('(')[0], false);
    const tt = pgType((tpk?.type || 'INT').split('(')[0], false);
    const od = rel.onDelete || 'CASCADE', ou = rel.onUpdate || 'CASCADE';
    const end = dialect === 'mysql' ? ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n' : ');\n';
    parts.push(
      `CREATE TABLE ${q(jn, dialect)} (\n` +
      `  ${q(sf, dialect)} ${st} NOT NULL,\n` +
      `  ${q(tf, dialect)} ${tt} NOT NULL,\n` +
      `  PRIMARY KEY (${q(sf, dialect)}, ${q(tf, dialect)}),\n` +
      `  FOREIGN KEY (${q(sf, dialect)}) REFERENCES ${q(src.name, dialect)}(${q(sc.name, dialect)}) ON DELETE ${od} ON UPDATE ${ou},\n` +
      `  FOREIGN KEY (${q(tf, dialect)}) REFERENCES ${q(tgt.name, dialect)}(${q(tc.name, dialect)}) ON DELETE ${od} ON UPDATE ${ou}\n` +
      end
    );
  }

  // FK constraints
  for (const rel of relationships) {
    if (rel.type === 'many-to-many') continue;
    const src = tmap[rel.sourceTableId], tgt = tmap[rel.targetTableId];
    const sc = cmap[rel.sourceColumnId], tc = cmap[rel.targetColumnId];
    if (!src || !tgt || !sc || !tc) continue;
    const od = rel.onDelete || 'RESTRICT', ou = rel.onUpdate || 'RESTRICT';
    const fk = `fk_${src.name}_${sc.name}`;
    const alter = dialect === 'mysql'
      ? `ALTER TABLE ${q(src.name, dialect)}\n  ADD CONSTRAINT ${q(fk, dialect)}\n  FOREIGN KEY (${q(sc.name, dialect)})\n  REFERENCES ${q(tgt.name, dialect)}(${q(tc.name, dialect)})\n  ON DELETE ${od} ON UPDATE ${ou};\n`
      : `ALTER TABLE ONLY ${q(src.name, dialect)}\n  ADD CONSTRAINT ${q(fk, dialect)}\n  FOREIGN KEY (${q(sc.name, dialect)})\n  REFERENCES ${q(tgt.name, dialect)}(${q(tc.name, dialect)})\n  ON DELETE ${od} ON UPDATE ${ou};\n`;
    parts.push(alter);
  }

  if (dialect === 'mysql') parts.push('\nSET FOREIGN_KEY_CHECKS=1;');
  return parts.join('\n');
}
